name: Publish to PyPI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install build
      - name: build package
        run: python -m build
      - name: publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
